SELECT * 
FROM  "ELUJOULISUSEINDEKS"."AASTASED"
WHERE "jykood" = 16147226
ORDER BY "AASTASED".aasta DESC
LIMIT 1;

SELECT * 
FROM  "ELUJOULISUSEINDEKS"."AASTASED"
WHERE "jykood" = 16147226
AND "maa_protsent" >= 0.9
ORDER BY "AASTASED".aasta DESC
LIMIT 1;